[functions]
directory = "functions/"

[build]
command = """
mkdir functions &&
cargo build --release --target x86_64-unknown-linux-musl &&
cp target/x86_64-unknown-linux-musl/release/opengraph-images functions/generate &&
cp target/x86_64-unknown-linux-musl/release/generic functions/generic &&
cp target/x86_64-unknown-linux-musl/release/og-test functions/og-test
"""
publish = "www"
