[functions]
directory = "functions/"

[build]
command = """
mkdir functions &&
cargo build --release --target x86_64-unknown-linux-musl --bin opengraph-images &&
cp target/x86_64-unknown-linux-musl/release/opengraph-images functions/generate
"""
publish = "src"
